name: Build x86_64 ISOs
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 2 * * 0'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  MATRIX_ROOM_ID: "!XXstZzLEcUVKyTcqCA:matrix.org"

jobs:
  prepare-release:
    runs-on: ubuntu-22.04
    steps:
      - id: time
        uses: boredland/get-time-action@dbc808befb89eb33fee64f5f4abce4d2a5fa7cfd # tag=2.0.0
        with:
          format: 'YYYYMMDDHHmm'
      - id: receive
        uses: boredland/kernel-info@main
    outputs:
      release_tag: ${{ steps.time.outputs.time }}
      longterm: ${{ steps.receive.outputs.longterm-pkg }}
      stable: ${{ steps.receive.outputs.stable-pkg }}
  build-stable:
    runs-on: ubuntu-22.04
    needs: [prepare-release]
    name: stable x86_64 ${{ matrix.edition }} ${{ matrix.branch }} ${{ matrix.scope }}
    permissions:
      contents: write
      actions: read
    strategy:
      fail-fast: false
      matrix:
        edition: [kde, xfce, gnome, i3, cinnamon]
        include:
          - kernel: ${{ needs.prepare-release.outputs.longterm }}
            branch: stable
            scope: full
          - edition: kde
            mention: "?"
          - edition: xfce
            mention: "?"
          - edition: gnome
            mention: "@yochananmarqos:matrix.org"
          - edition: i3
            mention: "@oberon-manjaro:matrix.org"
          - edition: cinnamon
            mention: "@oberon-manjaro:matrix.org"
    steps:
      - name: x86_64 build
        uses: manjaro/manjaro-iso-action@main
        with:
          iso-profiles-repo: https://gitlab.manjaro.org/profiles-and-settings/iso-profiles.git
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          kernel: ${{ matrix.kernel }}
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
      - uses: Tiryoh/gha-jobid-action@v1.2.0
        id: url
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: 'stable x86_64 ${{ matrix.edition }} ${{ matrix.branch }} ${{ matrix.scope }}'
      - uses: s3krit/matrix-message-action@v0.0.3
        if: failure()
        with:
          room_id: ${{ env.MATRIX_ROOM_ID}}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "⚠️ Error building for **x86**: [**${{ matrix.edition }}** - **${{ matrix.branch }}** - **${{ matrix.kernel }}**](${{ steps.url.outputs.html_url }}). Summon ${{ matrix.mention }} 🪄!"
          server: "matrix.org"
  build-unstable:
    runs-on: ubuntu-22.04
    needs: [prepare-release]
    name: unstable x86_64 ${{ matrix.edition }} ${{ matrix.branch }} ${{ matrix.scope }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        edition: [kde-dev, xfce, gnome-next, i3, cinnamon]
        include:
          - kernel: ${{ needs.prepare-release.outputs.stable }}
            branch: unstable
            scope: full
    steps:
      - name: x86_64 build
        uses: manjaro/manjaro-iso-action@main
        with:
          iso-profiles-repo: https://gitlab.manjaro.org/profiles-and-settings/iso-profiles.git
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          kernel: ${{ matrix.kernel }}
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
  announce:
    runs-on: ubuntu-22.04
    needs: [prepare-release, build-stable]
    if: needs.build-stable.result == 'success'
    steps:
      - uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ env.MATRIX_ROOM_ID}}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "🚀 Success building for **x86** (stable): Should we do a release? Check out [those](https://github.com/${{ github.repository }}/releases/tag/${{ needs.prepare-release.outputs.release_tag }}) assets!"
          server: "matrix.org"
  rollback:
    runs-on: ubuntu-22.04
    needs: [prepare-release, build-stable, build-unstable]
    if: cancelled() || failure()
    steps:
      - name: rollback
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          ASSET_COUNT=$(gh release view ${{ needs.prepare-release.outputs.release_tag }} --json "assets" --jq '.assets | length')
          # If we have more than the two tarballs github creates, we can delete the release - there is nothing to inspect
          if [ "$ASSET_COUNT" -gt "2" ]; then exit 0;fi
          gh release delete ${{ needs.prepare-release.outputs.release_tag }} -y --repo ${{ github.repository }}
      - uses: s3krit/matrix-message-action@v0.0.3
        if: ${{ needs.build-stable.result == 'failure' }}
        with:
          room_id: ${{ env.MATRIX_ROOM_ID}}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "😬 Error building for **x86**: Please have a look into the [logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          server: "matrix.org"