name: Build x86_64 ISOs
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 2 * * 0'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  MATRIX_ROOM_ID: "!XXstZzLEcUVKyTcqCA:matrix.org"

jobs:
  prepare-release:
    runs-on: ubuntu-22.04
    steps:
      - id: time
        uses: boredland/get-time-action@dbc808befb89eb33fee64f5f4abce4d2a5fa7cfd # tag=2.0.0
        with:
          format: 'YYYYMMDDHHmm'
      - id: receive
        uses: boredland/kernel-info@main
    outputs:
      release_tag: ${{ steps.time.outputs.time }}
      longterm: ${{ steps.receive.outputs.longterm-pkg }}
      stable: ${{ steps.receive.outputs.stable-pkg }}
  build-stable:
    runs-on: ubuntu-22.04
    needs: [prepare-release]
    continue-on-error: false
    name: x86_64 ${{ matrix.edition }} ${{ matrix.branch }} ${{ matrix.scope }}
    permissions:
      contents: write
    strategy:
      matrix:
        edition: [kde, xfce, gnome, i3, cinnamon]
        branch: [stable]
        scope: [full]
        include:
          - kernel: ${{ needs.prepare-release.outputs.longterm }}
    steps:
      - name: x86_64 build
        uses: manjaro/manjaro-iso-action@main
        with:
          iso-profiles-repo: https://gitlab.manjaro.org/profiles-and-settings/iso-profiles.git
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          kernel: ${{ matrix.kernel }}
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
  build-unstable:
    runs-on: ubuntu-22.04
    needs: [prepare-release]
    continue-on-error: true
    name: x86_64 ${{ matrix.edition }} ${{ matrix.branch }} ${{ matrix.scope }}
    permissions:
      contents: write
    strategy:
      matrix:
        edition: [kde-dev, xfce, gnome-next, i3, cinnamon]
        branch: [unstable]
        scope: [full]
        include:
          - kernel: ${{ needs.prepare-release.outputs.stable }}
    steps:
      - name: x86_64 build
        uses: manjaro/manjaro-iso-action@main
        with:
          iso-profiles-repo: https://gitlab.manjaro.org/profiles-and-settings/iso-profiles.git
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          kernel: ${{ matrix.kernel }}
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
  rollback:
    runs-on: ubuntu-22.04
    needs: [prepare-release, build-stable]
    if: cancelled() || failure()
    steps:
      - name: rollback
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          ASSET_COUNT=$(gh release view ${{ needs.prepare-release.outputs.release_tag }} --json "assets" --jq '.assets | length')
          # If we have more than the two tarballs github creates, we can delete the release - there is nothing to inspect
          if [ "$ASSET_COUNT" -gt "2" ]; then exit 0;fi
          gh release delete ${{ needs.prepare-release.outputs.release_tag }} -y --repo ${{ github.repository }}
          git push --delete origin ${{ needs.prepare-release.outputs.release_tag }}
      - uses: s3krit/matrix-message-action@v0.0.3
        if: ${{ needs.build-stable.result == 'failure' }}
        with:
          room_id: ${{ env.MATRIX_ROOM_ID}}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "😬 Error building for **x86**: Please have a look into the [logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          server: "matrix.org"